/*INSERT INTO бренд VALUES (1,"6MX");
INSERT INTO бренд VALUES (2,"Adriatica");
INSERT INTO бренд VALUES (3,"Anne Klein");
INSERT INTO бренд VALUES (4,"Armand Nicolet");
INSERT INTO бренд VALUES (5,"Armani Exchange");
INSERT INTO бренд VALUES (6,"Armin Strom");
INSERT INTO бренд VALUES (7,"Auguste Reymond");
INSERT INTO бренд VALUES (8,"Aviator");
INSERT INTO бренд VALUES (9,"BALL");
INSERT INTO бренд VALUES (10,"Balmain");
INSERT INTO бренд VALUES (11,"Boccia Titanium");
INSERT INTO бренд VALUES (12,"Bomberg");
INSERT INTO бренд VALUES (13,"Calvin Klein");
INSERT INTO бренд VALUES (14,"Candino");
INSERT INTO бренд VALUES (15,"Carl von Zeyten");
INSERT INTO бренд VALUES (16,"Casio");
INSERT INTO бренд VALUES (17,"Certina");
INSERT INTO бренд VALUES (18,"Citizen");
INSERT INTO бренд VALUES (19,"Continental");
INSERT INTO бренд VALUES (20,"Cornavin");
INSERT INTO бренд VALUES (21,"Corum");
INSERT INTO бренд VALUES (22,"Cuervo y Sobrinos");
INSERT INTO бренд VALUES (23,"CYSTOS");
INSERT INTO бренд VALUES (24,"D1 Milano");
INSERT INTO бренд VALUES (25,"Daniel Klein");
INSERT INTO бренд VALUES (26,"Daniel Wellington");
INSERT INTO бренд VALUES (27,"DAYOSA");
INSERT INTO бренд VALUES (28,"Delbana");
INSERT INTO бренд VALUES (29,"Delma");
INSERT INTO бренд VALUES (30,"Diesel");
INSERT INTO бренд VALUES (31,"DKNY");
INSERT INTO бренд VALUES (32,"Doodle");
INSERT INTO бренд VALUES (33,"Ducati");
INSERT INTO бренд VALUES (34,"Elysee");
INSERT INTO бренд VALUES (35,"Emporio Armani");
INSERT INTO бренд VALUES (36,"Epos");
INSERT INTO бренд VALUES (37,"Festina");
INSERT INTO бренд VALUES (38,"Fossil");
INSERT INTO бренд VALUES (39,"Freelook");
INSERT INTO бренд VALUES (40,"Furla");
INSERT INTO бренд VALUES (41,"Garmin");
INSERT INTO бренд VALUES (42,"Graham");
INSERT INTO бренд VALUES (43,"Gucci");
INSERT INTO бренд VALUES (44,"Guess");
INSERT INTO бренд VALUES (45,"Hugo Boss");
INSERT INTO бренд VALUES (46,"Invicta");
INSERT INTO бренд VALUES (47,"Jacques Lemans");
INSERT INTO бренд VALUES (48,"L Duchen");
INSERT INTO бренд VALUES (49,"Lee Cooper");
INSERT INTO бренд VALUES (50,"Mathey-Tissot");
INSERT INTO бренд VALUES (51,"Orient");
INSERT INTO бренд VALUES (52,"Q&Q");
INSERT INTO бренд VALUES (53,"Rodania");
INSERT INTO бренд VALUES (54,"Santa Barbara Polo & Racquet");
INSERT INTO бренд VALUES (55,"Seiko");
INSERT INTO бренд VALUES (56,"SOKOLOV");
INSERT INTO бренд VALUES (57,"Stuhrling");
INSERT INTO бренд VALUES (58,"TAG Hever");
INSERT INTO бренд VALUES (59,"Tommy Hilfiger");
INSERT INTO бренд VALUES (60,"Versace");
INSERT INTO бренд VALUES (61,"Vostok Europe");
INSERT INTO бренд VALUES (62,"Wainer");
INSERT INTO бренд VALUES (63,"Михаил Москвитин");
INSERT INTO бренд VALUES (64,"Восток"); */
SELECT * FROM бренд